version: '3'

services:
  db:
    image: mariadb:latest
    container_name: data
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress-net

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: script
    volumes:
      - ./src:/var/www/html
    networks:
      - wordpress-net
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: http
    ports:
      - "8080:8080"
    volumes:
      - ./src:/var/www/html
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - wordpress-net
    depends_on:
      - php

networks:
  wordpress-net:
    driver: bridge

volumes:
  db_data:
